import os
import unittest


class AdminTemplateSchemaTest(unittest.TestCase):
    def test_admin_html_loads_shared_admin_schema(self):
        project_root = os.path.dirname(os.path.dirname(__file__))
        admin_html = os.path.join(project_root, 'templates', 'admin.html')
        admin_json = os.path.join(project_root, 'templates', 'admin.json')

        with open(admin_html, encoding='utf-8') as f:
            html = f.read()
        with open(admin_json, encoding='utf-8') as f:
            schema = f.read()

        self.assertIn('"title": "统一账户驾驶舱"', schema)
        self.assertIn('"title": "账户资金"', schema)
        self.assertIn('"title": "资产归属"', schema)
        self.assertIn('"title": "杠杆负债"', schema)
        self.assertIn('"title": "半套与 CTA 风险"', schema)
        self.assertIn('现货/杠杆底仓', schema)
        self.assertIn('当前半套和 CTA 仍是两套逻辑', schema)
        self.assertIn('"id": "u:unified_base_asset_buy_wizard"', schema)
        self.assertIn('"title": "1 预览"', schema)
        self.assertIn('"title": "2 确认执行"', schema)
        self.assertIn('启动统一账户半套', schema)
        self.assertIn('停止统一账户半套', schema)
        self.assertIn('强制半套', schema)
        self.assertIn('/cta/unified/margin_rebalance/start', schema)
        self.assertIn('/cta/unified/margin_rebalance/stop', schema)
        self.assertIn('/cta/unified/margin_rebalance/force', schema)
        self.assertIn('"title": "半套 CTA Overlay"', schema)
        self.assertIn('部署 CTA overlay', schema)
        self.assertIn('启动 CTA overlay', schema)
        self.assertIn('停止 CTA overlay', schema)
        self.assertIn('加套 / 减套', schema)
        self.assertIn('调整 CTA 策略杠杆', schema)
        self.assertIn('CTA策略杠杆 trade_ratio', schema)
        self.assertIn('CTA推荐投入(USDT，可覆盖)', schema)
        self.assertIn('当前推荐覆盖剩余半仓', schema)
        self.assertIn('半套空头负责固定对冲，CTA overlay 负责剩余半仓的趋势暴露', schema)
        self.assertIn('当前杠杆对应推荐投入', schema)
        self.assertIn('"title": "完整半套模式"', schema)
        self.assertIn('"title": "完整半套 CTA Overlay 列表"', schema)
        self.assertIn('"id": "u:unified_halfset_mode"', schema)
        self.assertIn('"id": "u:unified_halfset_overlays"', schema)
        self.assertIn('半套和CTA只记账，真实U本位仓位由协调器合成', schema)
        self.assertIn('配置完整半套', schema)
        self.assertIn('启动完整半套', schema)
        self.assertIn('暂停完整半套', schema)
        self.assertIn('同步上一信号', schema)
        self.assertIn('预览协调', schema)
        self.assertIn('执行协调', schema)
        self.assertIn('/cta/unified/halfset/summary', schema)
        self.assertIn('/cta/unified/halfset/configure', schema)
        self.assertIn('/cta/unified/halfset/start', schema)
        self.assertIn('/cta/unified/halfset/stop', schema)
        self.assertIn('/cta/unified/halfset/reconcile/preview', schema)
        self.assertIn('/cta/unified/halfset/reconcile/execute', schema)
        self.assertIn('/cta/unified/halfset/sync_last_signal', schema)
        self.assertIn('/cta/unified/halfset/overlay/list', schema)
        self.assertIn('/cta/unified/halfset/overlay/deploy', schema)
        self.assertIn('/cta/unified/halfset/overlay/start', schema)
        self.assertIn('/cta/unified/halfset/overlay/stop', schema)
        self.assertIn('/cta/unified/halfset/overlay/update', schema)
        self.assertIn('/cta/unified/halfset/overlay/delete', schema)
        self.assertIn('"name": "weight"', schema)
        self.assertIn('"name": "target_qty"', schema)
        self.assertIn('"name": "recommended_cta_init_value"', schema)
        self.assertIn('"name": "recommended_cta_init_value_by_ratio"', schema)
        self.assertIn('"name": "recommended_cta_base_qty"', schema)
        self.assertIn('"name": "cta_exposure_if_long"', schema)
        self.assertIn('"name": "cta_exposure_if_flat"', schema)
        self.assertIn('"name": "cta_exposure_if_short"', schema)
        self.assertIn('交易所合约杠杆', schema)
        self.assertIn('/cta/unified/overlay/summary', schema)
        self.assertIn('/cta/unified/overlay/deploy', schema)
        self.assertIn('/cta/unified/overlay/update_cta', schema)
        self.assertIn('/cta/unified/overlay/update_rebalance', schema)
        self.assertIn('"name": "rebalance_running"', schema)
        self.assertIn('"name": "live_trade_enabled"', schema)
        self.assertIn('"name": "last_rebalance_time"', schema)
        self.assertIn('"name": "position_gap"', schema)
        self.assertIn('"name": "next_action_hint"', schema)
        self.assertIn('"name": "base_notional_qty"', schema)
        self.assertIn('"label": "折算币数量"', schema)
        self.assertIn('检测到币本位', schema)
        self.assertNotIn('统一账户底仓买入 - 先预览', schema)
        self.assertNotIn('统一账户底仓买入 - 确认执行', schema)
        self.assertNotIn('"title": "账户拓扑"', schema)
        self.assertNotIn('"title": "钱包拓扑"', schema)
        self.assertNotIn('"title": "资产桶明细"', schema)
        self.assertNotIn('"title": "现货/杠杆负债"', schema)
        self.assertNotIn('"title": "半套与策略暴露"', schema)
        self.assertIn('/admin/schema', html)
        self.assertNotIn('let amisJSON = {', html)


if __name__ == '__main__':
    unittest.main()
