CREATE TABLE IF NOT EXISTS `cta_unified_halfset_mode` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `strategy` varchar(255) NOT NULL DEFAULT '' COMMENT '统一账户策略名称',
  `asset` varchar(64) NOT NULL DEFAULT '' COMMENT '现货/杠杆底仓资产',
  `spot_symbol` varchar(64) NOT NULL DEFAULT '' COMMENT '底仓买入交易对',
  `hedge_symbol` varchar(64) NOT NULL DEFAULT '' COMMENT 'U本位协调交易对',
  `cta_key` varchar(255) NOT NULL DEFAULT '' COMMENT 'CTA策略唯一标识',
  `interval` varchar(64) NOT NULL DEFAULT '4h' COMMENT 'CTA周期',
  `cta` varchar(255) NOT NULL DEFAULT 'adapt_bolling_anti_chase' COMMENT 'CTA策略名称',
  `period` varchar(255) NOT NULL DEFAULT '[200,20]' COMMENT 'CTA参数',
  `hedge_ratio` decimal(10,4) NOT NULL DEFAULT '0.5000' COMMENT '半套比例',
  `cta_sizing_mode` varchar(32) NOT NULL DEFAULT 'auto_remaining' COMMENT 'CTA仓位模式',
  `cta_budget_usd` decimal(20,4) NOT NULL DEFAULT '0.0000' COMMENT '手动CTA名义USDT',
  `cta_trade_ratio` decimal(10,4) NOT NULL DEFAULT '1.0000' COMMENT 'CTA策略杠杆',
  `is_running` tinyint NOT NULL DEFAULT '0' COMMENT '是否启用完整半套模式',
  `live_trade_enabled` tinyint NOT NULL DEFAULT '0' COMMENT '是否允许协调器真实下单',
  `half_target_qty` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '半套记账目标',
  `cta_target_qty` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT 'CTA记账目标',
  `total_target_qty` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT 'U本位合成目标',
  `current_um_position` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '当前交易所U本位仓位',
  `order_delta_qty` decimal(20,8) NOT NULL DEFAULT '0.00000000' COMMENT '待协调下单差额',
  `last_signal` int NOT NULL DEFAULT '0' COMMENT '最近CTA信号',
  `last_signal_time` datetime DEFAULT NULL COMMENT '最近CTA信号时间',
  `last_reconcile_time` datetime DEFAULT NULL COMMENT '最近协调时间',
  `last_status` int NOT NULL DEFAULT '0' COMMENT '最近协调状态',
  `last_msg` varchar(255) NOT NULL DEFAULT '' COMMENT '最近协调提示',
  `is_del` tinyint NOT NULL DEFAULT '0' COMMENT '是否软删除',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_strategy_asset` (`strategy`, `asset`, `is_del`),
  KEY `idx_cta_key` (`cta_key`),
  KEY `idx_strategy_symbol` (`strategy`, `hedge_symbol`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='统一账户完整半套模式';
